apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pytestxdist.jtes.net
spec:
  scope: Namespaced
  group: jtes.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                num_nodes:
                  type: integer
                image:
                  type: string
                socket_server_port:
                  type: integer
                pytest_dir:
                  type: string
                extra_pytest_args:
                  type: array
                  items:
                    type: string
  names:
    kind: PytestXdist
    plural: pytestxdist
    singular: pytestxdist
