apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pytest-xdist-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pytest-xdist-operator
subjects:
  - kind: ServiceAccount
    name: pytest-xdist-operator
    namespace: default
