apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pytest-xdist-operator
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]
- apiGroups: ["jtes.net"]
  resources: ["pytestxdist"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
